Various scripts and such used to create dictionary candidates for
nob2smj and nob2sma from nob2sme dictionary + corpora.

* Prerequisites
  The main prerequisites are

  - [[http://giellatekno.uit.no/doc/ling/CorpusTools.html][CorpusTools]]
  - the sme/nob/sma/smj analysers from $GTHOME/langs
  - all sme/nob/sma/smj-related folders from $GTHOME/words/dicts

  See [[http://giellatekno.uit.no/doc/infra/GettingStarted.html]] for how
  to set things up – there's no need to mess up your ~/.bashrc, but
  you'll need to set at least the $GTHOME/$GTFREE/$GTCORE (optionally
  $GTBOUND) variables, and for now the Xerox tools (xfst/lookup etc.)
  are needed.

* Running the candidate generation

  Run =make= to make the stuff; the first time around you need to also
  run =make corpus=.

  The results will appear in the =out/= directory, where e.g.
  =out/smesmj= has a two-column format where the first word is a sme
  input and the second is a smj candidate.

  The files in =out/nobsmjsme= and =out/nobsmasme= include both nob
  and sme translations for the candidates, annotated with normalised
  frequencies for all the three words. The format is, tab-separated:

  : nob 	candidate	sme	fr_nob	fr_candidate	fr_sme	in_FST

  All file names start with a part of speech (V, N, A or nonVNA for
  "the rest"). The in_FST field is 1 iff the candidate had an analysis
  from =$GTHOME/langs/${lang}/src/analyser-gt-desc.xfst= with the
  right part of speech.
  
** Running the candidate-respelling
  … currently uses some ocaml stuff, TODO

* TODO stuff
See [[file:TODO.org][TODO.org]].
