* TODO add "word-lists" to corpus before make-freq?

* TODO also try non-fad words for the sources that give the best candidates
  or for high frequency candidates etc.

* TODO simple rules for loans
  | nob          | smj            | sme           |
  |--------------+----------------+---------------|
  | transkribere | transkribierit | transkriberit |
  | initiere     | initieret      | initieret     |

  If we need nob, we can't rely on xfst alone.

* TODO kintel, for nobsmj
* TODO pretty.sh should include a "source" field or something
  when we get kintel in there, we need to differentiate if something
  came from nobsmj or smesmj

* TODO shorten corpora to size of the smallest for comparable frequencies?
  Currently, =pretty.sh= will simply divide the sum of the larger by
  the sum of the smallest corpus.

* TODO use forms or lms for frequency?
  Some of the dictionary entries are have 0 hits in lms, but hits in
  forms (TV-nyheter), but we still get less 0's by using lms

  Could lemmatise before looking up frequency, but this is complicated
  enough already …

* TODO kwic-annotate out-files
